#!/usr/bin/env python
#!/usr/bin/env python
import sys
import urllib, urllib2
import re
import subprocess
from datetime import datetime
import simplejson as json
from git import *


POST_URL = 'http://127.0.0.1:8000/json/'
REPO_URL = 'http://example.com'
COMMIT_URL = r'http://example.com/commit/%s'
REPO_NAME = 'gitrepo'
REPO_OWNER_NAME = 'Git U. Some'
REPO_OWNER_EMAIL = 'git@example.com'
REPO_DESC = ''

def post(url, data):
    u = urllib2.urlopen(POST_URL, urllib.urlencode({'payload': data}))
    u.read()
    u.close()

def recuperarCommit():

	repo=Repo('/home/gary/qosoftware/testrepository1')
	commit = repo.commits()[0]
	mensaje = commit.message
	name = commit.committer.name
	data = {'nombre':name,'mensaje':mensaje}
	return json.dumps(data)

if __name__ == '__main__':
	datos = recuperarCommit()
	post(POST_URL, datos)
