#! /usr/bin/env python
from pysqlite2 import dbapi2 as sqlite

conn = sqlite.connect("../../database.db")
cursor = conn.cursor()
cursor.execute("DELETE FROM microblog_entrada_recipientes WHERE entrada_id IN(SELECT id FROM microblog_entrada WHERE contenido='Prueba publicacion')")
cursor.execute("DELETE FROM microblog_entrada WHERE contenido='Prueba publicacion'")

conn.commit()
cursor.close()
